# Generated by Django 5.1.5 on 2025-02-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='verify_code',
            new_name='verification_code',
        ),
    ]
